//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Insight.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project_Insight.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Artanis {
            get {
                object obj = ResourceManager.GetObject("Artanis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Génesis
        ///Éxodo
        ///Levítico
        ///Números
        ///Deuteronomio
        ///Josué
        ///Jueces
        ///Rut
        ///1 Samuel
        ///2 Samuel
        ///1 Reyes
        ///2 Reyes
        ///1 Crónicas
        ///2 Crónicas
        ///Esdras
        ///Nehemías
        ///Ester
        ///Job
        ///Salmos
        ///Proverbios
        ///Eclesiastés
        ///El Cantar de los Cantares
        ///Isaías
        ///Jeremías
        ///Lamentaciones
        ///Ezequiel
        ///Daniel
        ///Oseas
        ///Joel
        ///Amós
        ///Abdías
        ///Jonás
        ///Miqueas
        ///Nahúm
        ///Habacuc
        ///Sofonías
        ///Ageo
        ///Zacarías
        ///Malaquías
        ///Mateo
        ///Marcos
        ///Lucas
        ///Juan
        ///Hechos
        ///Romanos
        ///1 Corintios
        ///2 Corintios
        ///Gálatas
        ///Efesios
        ///Filipenses
        ///Colosenses
        ///1 Tesalonicenses
        ///2 Tesalonicen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bible_Books {
            get {
                return ResourceManager.GetString("Bible_Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of commands:
        ///&quot;new&quot;  + month (only first 3 chars)
        ///&quot;open&quot; -&gt; popups an OpenFileDialog
        ///&quot;exit&quot; -&gt; Close all the application
        ///&quot;save&quot; + Specify &quot;vym&quot;, &quot;rp&quot;, &quot;ac&quot;, &quot;all&quot;
        ///&quot;tab&quot;  + Specify &quot;vym&quot;, &quot;rp&quot;, &quot;ac&quot;
        ///&quot;week&quot; + valid int (between 1 to 4 or 5 if applies)
        ///&quot;conv&quot; + name of the convention (set current week as convention)
        ///	   + &quot;false&quot; to set normal a convention week.
        ///&quot;afil&quot; -&gt; Autofill the fields
        ///&quot;help&quot; -&gt; To display all the current commands
        ///&quot;vst&quot;  + &quot;true&quot; or &quot;false&quot; to set current week for the visi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Commands_Helper {
            get {
                return ResourceManager.GetString("Commands_Helper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkTemplar {
            get {
                object obj = ResourceManager.GetObject("DarkTemplar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DB {
            get {
                object obj = ResourceManager.GetObject("DB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Executor {
            get {
                object obj = ResourceManager.GetObject("Executor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FenixDragoon {
            get {
                object obj = ResourceManager.GetObject("FenixDragoon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FenixZealot {
            get {
                object obj = ResourceManager.GetObject("FenixZealot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HunterKiller {
            get {
                object obj = ResourceManager.GetObject("HunterKiller", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hybrid {
            get {
                object obj = ResourceManager.GetObject("Hybrid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Noise {
            get {
                object obj = ResourceManager.GetObject("Noise", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Oracle {
            get {
                object obj = ResourceManager.GetObject("Oracle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Programs {
            get {
                object obj = ResourceManager.GetObject("Programs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geoplazas Qro.
        ///True
        ///19:00
        ///19:00
        ///Tuesday
        ///Saturday
        ///True.
        /// </summary>
        internal static string Project_Insight_Config {
            get {
                return ResourceManager.GetString("Project_Insight_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap protoss_Frame {
            get {
                object obj = ResourceManager.GetObject("protoss_Frame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Selendis {
            get {
                object obj = ResourceManager.GetObject("Selendis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
