//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Insight.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project_Insight.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Artanis {
            get {
                object obj = ResourceManager.GetObject("Artanis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Génesis
        ///Éxodo
        ///Levítico
        ///Números
        ///Deuteronomio
        ///Josué
        ///Jueces
        ///Rut
        ///1 Samuel
        ///2 Samuel
        ///1 Reyes
        ///2 Reyes
        ///1 Crónicas
        ///2 Crónicas
        ///Esdras
        ///Nehemías
        ///Ester
        ///Job
        ///Salmos
        ///Proverbios
        ///Eclesiastés
        ///El Cantar de los Cantares
        ///Isaías
        ///Jeremías
        ///Lamentaciones
        ///Ezequiel
        ///Daniel
        ///Oseas
        ///Joel
        ///Amós
        ///Abdías
        ///Jonás
        ///Miqueas
        ///Nahúm
        ///Habacuc
        ///Sofonías
        ///Ageo
        ///Zacarías
        ///Malaquías
        ///Mateo
        ///Marcos
        ///Lucas
        ///Juan
        ///Hechos
        ///Romanos
        ///1 Corintios
        ///2 Corintios
        ///Gálatas
        ///Efesios
        ///Filipenses
        ///Colosenses
        ///1 Tesalonicenses
        ///2 Tesalonicen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bible_Books {
            get {
                return ResourceManager.GetString("Bible_Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkTemplar {
            get {
                object obj = ResourceManager.GetObject("DarkTemplar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Executor {
            get {
                object obj = ResourceManager.GetObject("Executor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FenixDragoon {
            get {
                object obj = ResourceManager.GetObject("FenixDragoon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FenixZealot {
            get {
                object obj = ResourceManager.GetObject("FenixZealot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HunterKiller {
            get {
                object obj = ResourceManager.GetObject("HunterKiller", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hybrid {
            get {
                object obj = ResourceManager.GetObject("Hybrid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Noise {
            get {
                object obj = ResourceManager.GetObject("Noise", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Oracle {
            get {
                object obj = ResourceManager.GetObject("Oracle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap protoss_Frame {
            get {
                object obj = ResourceManager.GetObject("protoss_Frame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Selendis {
            get {
                object obj = ResourceManager.GetObject("Selendis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las cualidades principales de Jehová
        ///Tu nombre es Jehová
        ///Tú me das fuerza, confianza y valor
        ///“Jehová es mi Pastor”
        ///Las maravillosas obras de Dios
        ///Los cielos proclaman la gloria de Dios
        ///Jehová es mi fuerza y mi salvación
        ///Jehová es mi Refugio
        ///¡Jehová es nuestro Rey!
        ///¡Alabemos a nuestro Dios, Jehová!
        ///La creación alaba a Jehová
        ///Jehová, nuestro gran Dios
        ///Cristo es nuestro modelo
        ///Honremos al nuevo Rey de la Tierra
        ///Alabemos al Primogénito de Jehová
        ///Alabemos a Jehová por su Hijo, el Ungido
        ///“Quiero”        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Songs_List {
            get {
                return ResourceManager.GetString("Songs_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Conoce usted bien a Dios?
        ///¿Sera usted sobreviviente de los últimos días?
        ///Avancemos con la organizacion unida de Jehova
        ///El mundo que nos rodea prueba que Dios existe
        ///Ayuda practica para las familias
        ///¿Que aprendemos del Diluvio de los dıas de Noe?
        ///Imitemos al “Padre de tiernas misericordias”
        ///Vivamos para hacer la voluntad de Dios, no la nuestra
        ///Nunca permitamos que se nos embote el oıdo
        ///Conduciendonos honradamente en todo tiempo
        ///‘No ser parte del mundo’... a semejanza de Cristo
        ///El respeto a la aut [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Speech_list {
            get {
                return ResourceManager.GetString("Speech_list", resourceCulture);
            }
        }
    }
}
